language: java
script:
  - mvn clean
  - mvn package
  - java -jar target/cardServiceJava-BasicInfo-shaded.jar
  - mvn exec:java -Dexec.mainClass=RPCClient
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# https://docs.travis-ci.com/user/build-stages/     stage build tutorial