language: java
script:
  - mvn clean
  - mvn package
  - docker build -f Dockerfile -t tps/full-info:8 .
deploy:
  provider: heroku
  api_key:
    secure: 7d043b6f-9072-410f-9fef-f0d50cfd4974
  app: tps-full-info
