language: java
script:
  - mvn clean
  - mvn package
  - docker build -f Dockerfile -t tps/full-info:8 .
deploy:
  provider: heroku
  api_key:
    secure: 7d043b6f-9072-410f-9fef-f0d50cfd4974
  app: tps-full-info
#  - docker run -it  -p 8080:8080 tps/basic-info:8
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# https://docs.travis-ci.com/user/build-stages/     stage build tutorial